# Generated by Django 5.2.10 on 2026-01-28 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='face_images/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_images', models.ManyToManyField(related_name='images', to='api.faceimage')),
            ],
        ),
        migrations.CreateModel(
            name='OutputVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_swapped_video', models.FileField(upload_to='swapped_videos/')),
                ('background_changed_video', models.FileField(upload_to='background_changed_videos/')),
                ('audio_extracted', models.FileField(blank=True, null=True, upload_to='extracted_audios/')),
                ('final_video', models.FileField(upload_to='output_videos/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_videos', to='api.videodata')),
            ],
        ),
    ]
