# Generated by Django 5.2.10 on 2026-01-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputvideo",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videodata",
            name="video_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="outputvideo",
            name="background_changed_video",
            field=models.FileField(
                blank=True, null=True, upload_to="background_changed_videos/"
            ),
        ),
        migrations.AlterField(
            model_name="outputvideo",
            name="face_swapped_video",
            field=models.FileField(blank=True, null=True, upload_to="swapped_videos/"),
        ),
        migrations.AlterField(
            model_name="outputvideo",
            name="final_video",
            field=models.FileField(blank=True, null=True, upload_to="output_videos/"),
        ),
        migrations.AlterField(
            model_name="outputvideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="videodata",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
