# Generated by Django 5.2.10 on 2026-01-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_outputvideo_progress_videodata_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputvideo',
            name='background_changed_video',
        ),
        migrations.RemoveField(
            model_name='outputvideo',
            name='face_swapped_video',
        ),
        migrations.AddField(
            model_name='outputvideo',
            name='final_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
